import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menu } from "@/COMMON/Menu";
import { Grid } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Menu />
        <Grid container sx={{width:"100%",height:"93vh",p:1.5}}>
        {children}
        </Grid>
      </body>
    </html>
  );
}
